// Preserved & curated from web-legacy/src/global.js
// Images — legacy assets copied to src/assets/legacy-img

export const profile = {
  name: "Ariel Francis Gacilo",
  short: "Ariel Francis Fernando Gacilo",
  title: "Senior Frontend & Game Developer",
  tagline: "Building high-performance interactive experiences, games and modern web applications.",
  summary: "10+ years shipping production web platforms and real-time casino games. Frontend architecture, PixiJS/WebGL rendering, and scalable full-stack delivery — from Figma to App Store and production infra.",
  location: "Bongabong, Oriental Mindoro, Philippines 5211",
  phone: "+63 998 036 4770",
  email: "gaciloarielfrancis@gmail.com",
  linkedin: "https://www.linkedin.com/in/ariel-francis-gacilo-01a694b0/",
  skype: "gaciloarielfrancis",
  github: "https://github.com/gaciloarielfrancis",
};

export const stats = [
  { label: "Years shipping", value: "10+", sub: "2014 — present" },
  { label: "Production games", value: "9", sub: "PixiJS + WebGL" },
  { label: "Platforms delivered", value: "13", sub: "Games + web apps + tools" },
  { label: "Tech stack", value: "27", sub: "Across the portfolio" },
];

export const skillGroups = [
  {
    title: "Frontend",
    accent: "#7c5cff",
    items: [
      { n: "React", level: 10, years: 3 },
      { n: "TypeScript", level: 10, years: 3 },
      { n: "JavaScript", level: 10, years: 9 },
      { n: "HTML5", level: 10, years: 9 },
      { n: "CSS3", level: 10, years: 9 },
      { n: "Tailwind CSS", level: 10, years: 3 },
      { n: "Vue.js", level: 8, years: 2 },
      { n: "Redux", level: 10, years: 3 },
      { n: "Next.js", level: 7, years: 1 },
      { n: "Vite", level: 9, years: 2 },
      { n: "Webpack", level: 10, years: 3 },
      { n: "Material UI", level: 10, years: 2 },
      { n: "Bootstrap", level: 10, years: 9 },
      { n: "jQuery", level: 10, years: 9 },
      { n: "Ionic", level: 8, years: 3 },
    ],
  },
  {
    title: "Game Development",
    accent: "#22d3ee",
    items: [
      { n: "PixiJS", level: 10, years: 3 },
      { n: "Phaser", level: 8, years: 2 },
      { n: "GSAP", level: 10, years: 9 },
      { n: "React Spring", level: 7, years: 2 },
      { n: "Babylon.js", level: 8, years: 2 },
      { n: "WebGL / Canvas", level: 9, years: 4 },
    ],
  },
  {
    title: "Backend & Data",
    accent: "#f472b6",
    items: [
      { n: "Node.js", level: 9, years: 7 },
      { n: "PHP", level: 10, years: 7 },
      { n: "Symfony", level: 10, years: 3 },
      { n: "Python", level: 8, years: 2 },
      { n: "PostgreSQL", level: 10, years: 3 },
      { n: "MySQL / MySQLi", level: 10, years: 7 },
      { n: "MongoDB", level: 8, years: 2 },
      { n: "Firebase", level: 7, years: 2 },
    ],
  },
  {
    title: "Tooling & Infra",
    accent: "#a3e635",
    items: [
      { n: "Axios", level: 10, years: 5 },
      { n: "Git & GitHub", level: 10, years: 9 },
      { n: "SEO / Open Graph", level: 9, years: 6 },
      { n: "Performance Opt.", level: 9, years: 7 },
      { n: "App Store Deploy", level: 8, years: 4 },
    ],
  },
];

export const aboutCards = [
  {
    k: "Frontend Engineering",
    d: "Modern web apps, UI architecture, state management and performance — shipping maintainable, testable interfaces that scale with teams.",
    icon: "◈",
  },
  {
    k: "Game Development",
    d: "Real-time game UI, animation systems and rendering pipelines. PixiJS + GSAP on Canvas/WebGL, built for 60fps on low-end devices.",
    icon: "⬢",
  },
  {
    k: "Architecture",
    d: "Reusable component systems, API design, DB modeling and infra. From Figma → code → deploy, with SEO and asset optimization built-in.",
    icon: "⬣",
  },
  {
    k: "Leadership",
    d: "Collaborating with PMs, artists, animators and QA. Code reviews, technical direction, mentoring and owning delivery end-to-end.",
    icon: "⬔",
  },
];

export const experience = [
  {
    company: "Blueline Active Asia",
    role: "Game Developer",
    period: "Oct 2021 — Apr 2024",
    current: false,
    highlights: [
      "Built 8+ production casino games (PixiJS, TypeScript, GSAP, React) serving W88 — real-time multiplayer, certified RNG flows.",
      "Owned frontend rendering & animation pipeline; hit 60fps on mobile by atlas packing, tint batching and RAF scheduling.",
      "Collaborated across art, animation and QA — integrated Spine-ready assets and shrank load time via code-split + WebP.",
    ],
    stack: ["PixiJS", "TypeScript", "React", "GSAP", "Webpack"],
  },
  {
    company: "Smartest Guys in the Room",
    role: "Full-stack / Game Developer",
    period: "Jan 2016 — Oct 2021",
    current: false,
    highlights: [
      "Full-stack delivery for multiple client platforms — React/Vue frontends, PHP/Symfony + Node APIs, MySQL/PostgreSQL.",
      "Designed DB schemas, built reusable API modules and shipped to production servers and mobile stores.",
      "Led performance work: minification, sprite sheets, TinyPNG/WebP/WebM, OG/SEO and Lighthouse optimization.",
    ],
    stack: ["React", "Vue", "PHP", "Symfony", "Node.js", "MySQL"],
  },
  {
    company: "Immersive Media Inc.",
    role: "Senior Software Engineer",
    period: "Jan 2014 — Jan 2016",
    current: false,
    highlights: [
      "Senior engineering on early immersive web products — established frontend standards and delivery practices.",
    ],
    stack: ["JavaScript", "HTML5", "CSS3", "jQuery"],
  },
];

export const devRoles = [
  "Converting Figma / Photoshop / Illustrator into production code",
  "Collaborating with PM, graphic artists, animators and QA to hit quality bars",
  "Creating/modifying APIs and contributing reusable modules to the team",
  "Designing DB structure and server management",
  "Implementing SEO + Open Graph for discoverability",
  "Optimizing load time: minification, sprite sheets, TinyPNG, WebP/WebM, code-splitting",
  "Debugging, troubleshooting and production support",
  "Deploying to servers and to Google Play / App Store",
];

// Portfolio — curated from legacy; adds role/description per prompt guidance, no invented clients beyond existing
export const projects = [
  {
    slug: "dragon-tiger",
    name: "Dragon Tiger",
    category: "Casino Game",
    image: "dragon-tiger.jpg",
    role: "Game Developer — rendering, animation & game logic",
    description: "Real-time card game with deterministic animations and certified flow. Optimized for low-end mobile WebGL.",
    features: ["PixiJS scene graph", "GSAP choreography", "React shell + Webpack", "Mobile-first input"],
    challenge: "60fps card deal & reveal with zero jank on mid-tier Android.",
    solution: "Atlas batching, object pooling for cards, RAF-coalesced ticks and GPU-composited transforms.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=dragontiger&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "punto-banco",
    name: "Punto Banco",
    category: "Casino Game",
    image: "punto-banco.jpg",
    role: "Game Developer",
    description: "Baccarat variant — table state sync, chip physics and settlement animations.",
    features: ["State-driven UI", "Chip stacking", "Result reconciliation"],
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=puntobanco&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "three-faces",
    name: "Three Faces Baccarat",
    category: "Casino Game",
    image: "3-faces-baccarat.jpg",
    role: "Game Developer",
    description: "Three-hand baccarat with concurrent animations and side-bet UI.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=threefacesbaccarat&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "domino-qq",
    name: "Domino QQ Virtual Dealer",
    category: "Casino Game",
    image: "domino-qq.jpg",
    role: "Game Developer",
    description: "Domino QQ with virtual dealer — tile layout engine and turn sequencing.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=dominoqqvirtualdealer&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "golden-ball",
    name: "Golden Power Ball",
    category: "Lottery Game",
    image: "golden-power-ball.jpg",
    role: "Game Developer",
    description: "Number-draw lottery with ball physics and draw anticipation.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=goldenpowerball&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "hilo-card",
    name: "HiLo Card",
    category: "Casino Game",
    image: "hilo-card.jpg",
    role: "Game Developer",
    description: "Hi-Lo prediction game — minimal UI, instant feedback and streak tracking.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=hilocard&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "crypto-crash",
    name: "Crypto Crash",
    category: "Real-time Game",
    image: "crypto-crash.png",
    role: "Game Developer",
    description: "Multiplier curve game — real-time graph, cash-out timing and live player rail.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://games.crescendoops.com/Login?vendor=W88&s=&lang=en&game=cryptocrash&mode=try",
    featured: true,
  },
  {
    slug: "tambola",
    name: "Tambola Tropika",
    category: "Lottery",
    image: "tambola-tropika.jpg",
    role: "Game Developer",
    description: "Tambola/Housie — ticket generation, number calling and win validation.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=tambolatropika&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "keno",
    name: "Keno Mobile",
    category: "Lottery — Mobile",
    image: "keno.png",
    role: "Frontend / Game Developer",
    description: "Mobile Keno — touch-optimized board, quick-pick and draw history.",
    features: ["React + Redux", "PixiJS board", "React Spring transitions"],
    tech: ["HTML5", "JavaScript", "React", "Redux", "React Spring", "PixiJS"],
    link: "https://crescendogames.studio/Login?vendor=W88&s=&lang=en&game=newkeno&mode=try",
    featured: false,
  },
  {
    slug: "leiprime",
    name: "Lei Prime",
    category: "Corporate Platform",
    image: "leiprime.png",
    role: "Full-stack Developer",
    description: "Corporate site — React + Tailwind frontend on Symfony/PHP, SEO and CMS integration.",
    tech: ["HTML5", "JavaScript", "React", "Tailwind", "PHP", "Symfony", "MySQL"],
    link: "https://leiprime.com",
    featured: false,
  },
  {
    slug: "mdc",
    name: "My Dominion Corp",
    category: "Corporate Platform",
    image: "mdc.png",
    role: "Full-stack Developer",
    description: "Business platform — MUI + Tailwind, role-based content and Symfony API.",
    tech: ["HTML5", "JavaScript", "React", "Tailwind", "MUI", "PHP", "Symfony", "MySQL"],
    link: "https://mydominioncorp.com",
    featured: false,
  },
  {
    slug: "css-spritesheet",
    name: "CSS Spritesheet",
    category: "Dev Tool",
    image: "image-tools.svg",
    role: "Solo — open source",
    description: "Browser tool to pack images into CSS spritesheets — drag, pack, export.",
    tech: ["HTML5", "JavaScript", "CSS3"],
    link: "https://gaciloarielfrancis.github.io/CSS-Spritesheet/",
    featured: false,
  },
  {
    slug: "gif-to-spritesheet",
    name: "GIF to Spritesheet",
    category: "Dev Tool",
    image: "image-tools.svg",
    role: "Solo — open source",
    description: "Convert GIF frames into sprite sheets for game pipelines — built with Vite + React + Tailwind.",
    tech: ["HTML5", "TypeScript", "React", "Tailwind", "Vite"],
    link: "https://gaciloarielfrancis.github.io/GIF-To-Spritesheet",
    featured: true,
  },
];
