// Balanced Full-Stack + Game portfolio — curated from legacy + expanded for full-stack breadth
export const profile = {
  name: "Ariel Francis Gacilo",
  short: "Ariel Francis Fernando Gacilo",
  title: "Senior Full-Stack & Game Developer",
  tagline: "Building high-performance web platforms, games and APIs — from frontend to databases, servers and deployment.",
  summary: "10+ years shipping full-stack platforms and real-time games. I own the stack end-to-end: React/Vue frontends, Node/PHP/Symfony APIs, PostgreSQL/MySQL/MongoDB, server management (Nginx, PM2, Docker, Cloudflare) and store/server deployment — plus PixiJS/WebGL game rendering at 60fps.",
  location: "Roxas, Oriental Mindoro, Philippines 5212",
  phone: "+63 998 036 4770",
  email: "gaciloarielfrancis@gmail.com",
  linkedin: "https://www.linkedin.com/in/ariel-francis-gacilo-01a694b0/",
  skype: "gaciloarielfrancis",
  github: "https://github.com/gaciloarielfrancis",
};

export const stats = [
  { label: "Years shipping", value: "10+", sub: "2014 — present" },
  { label: "Full-stack platforms", value: "15", sub: "Games + portals + tools" },
  { label: "APIs & Databases", value: "8+", sub: "Node/PHP · Postgres/MySQL/Mongo" },
  { label: "Tech stack", value: "44", sub: "Frontend → Deployment" },
];

export const skillGroups = [
  {
    title: "Frontend",
    accent: "#7c5cff",
    items: [
      { n: "React", level: 10, years: 3 },
      { n: "TypeScript", level: 10, years: 5 },
      { n: "JavaScript", level: 10, years: 9 },
      { n: "HTML5", level: 10, years: 9 },
      { n: "CSS3", level: 10, years: 9 },
      { n: "Tailwind CSS", level: 10, years: 3 },
      { n: "Vue.js", level: 10, years: 4 },
      { n: "Redux", level: 10, years: 3 },
      { n: "Next.js", level: 7, years: 1 },
      { n: "Vite", level: 9, years: 2 },
      { n: "Webpack", level: 10, years: 3 },
      { n: "Material UI", level: 10, years: 2 },
      { n: "Bootstrap", level: 10, years: 9 },
      { n: "jQuery", level: 10, years: 9 },
      { n: "Ionic", level: 8, years: 3 },
    ],
  },
  {
    title: "Backend",
    accent: "#f472b6",
    items: [
      { n: "Node.js", level: 9, years: 7 },
      { n: "Express", level: 8, years: 5 },
      { n: "PHP", level: 10, years: 7 },
      { n: "Symfony", level: 10, years: 3 },
      { n: "Python", level: 8, years: 2 },
      { n: "REST APIs", level: 10, years: 7 },
      { n: "Axios", level: 10, years: 5 },
      { n: "Firebase", level: 7, years: 2 },
    ],
  },
  {
    title: "Databases",
    accent: "#22d3ee",
    items: [
      { n: "PostgreSQL", level: 10, years: 3 },
      { n: "MySQL / MySQLi", level: 10, years: 7 },
      { n: "MongoDB", level: 8, years: 2 },
      { n: "Prisma", level: 7, years: 1 },
      { n: "Database Design", level: 10, years: 7 },
    ],
  },
  {
    title: "Server & Deployment",
    accent: "#a3e635",
    items: [
      { n: "Nginx", level: 9, years: 6 },
      { n: "PM2", level: 9, years: 5 },
      { n: "Docker", level: 8, years: 3 },
      { n: "Cloudflare", level: 8, years: 4 },
      { n: "Git & GitHub", level: 10, years: 9 },
      { n: "GitHub Actions", level: 8, years: 3 },
      { n: "Linux Server Mgmt", level: 9, years: 7 },
      { n: "App Store Deploy", level: 8, years: 4 },
      { n: "SEO / Open Graph", level: 9, years: 6 },
      { n: "Performance Opt.", level: 9, years: 7 },
    ],
  },
  {
    title: "Game Development",
    accent: "#f59e0b",
    items: [
      { n: "PixiJS", level: 10, years: 3 },
      { n: "Phaser", level: 8, years: 2 },
      { n: "GSAP", level: 10, years: 9 },
      { n: "React Spring", level: 7, years: 2 },
      { n: "Babylon.js", level: 8, years: 2 },
      { n: "WebGL / Canvas", level: 9, years: 4 },
    ],
  },
];

export const aboutCards = [
  {
    k: "Frontend Engineering",
    d: "React, Vue, TypeScript, Tailwind — design systems, state management, performance budgets and maintainable UI that scales with teams.",
    icon: "◈",
  },
  {
    k: "Backend & APIs",
    d: "Node.js, PHP/Symfony, Python — REST APIs, auth, business logic and reusable modules. From Figma to API contract to client.",
    icon: "⬢",
  },
  {
    k: "Databases, Servers & Deployment",
    d: "PostgreSQL/MySQL/MongoDB schema design, Nginx/PM2/Docker, Cloudflare, CI/CD and store/server deploys. Owns the stack end-to-end.",
    icon: "⬣",
  },
  {
    k: "Game Development",
    d: "PixiJS/WebGL rendering, GSAP/Spine animations and real-time game UI — 60fps on low-end devices, certified flows.",
    icon: "◆",
  },
];

export const experience = [
  {
    company: "Blueline Active Asia",
    role: "Game Developer — Full-Stack Game Systems",
    period: "Oct 2021 — Apr 2024",
    current: false,
    highlights: [
      "Built 8+ production casino games (PixiJS, TypeScript, GSAP, React) for W88 — real-time multiplayer with Node/PHP APIs, MySQL/PostgreSQL and certified RNG.",
      "Owned frontend rendering & API integration; hit 60fps on mobile by atlas packing, tint batching, RAF scheduling and Nginx/PM2 + Cloudflare edge caching.",
      "Collaborated across art, animation and QA — shipped via Dockerized builds and optimized load with code-split + WebP/WebM.",
    ],
    stack: ["PixiJS", "TypeScript", "React", "GSAP", "Node.js", "MySQL", "Nginx", "Docker"],
  },
  {
    company: "Smartest Guys in the Room",
    role: "Full-stack / Game Developer",
    period: "Jan 2016 — Oct 2021",
    current: false,
    highlights: [
      "Full-stack delivery for client portals — React/Vue frontends, PHP/Symfony + Node/Express APIs, PostgreSQL/MySQL/MongoDB; designed schemas and reusable API modules.",
      "Managed Linux servers (Nginx, PM2, Docker), Cloudflare and GitHub Actions CI; handled DB design, server management and SEO/OG.",
      "Led performance: minification, sprite sheets, TinyPNG/WebP, Lighthouse, and deploys to production servers + Google Play/App Store.",
    ],
    stack: ["React", "Vue", "PHP", "Symfony", "Node.js", "Express", "PostgreSQL", "MySQL", "Nginx", "Docker"],
  },
  {
    company: "Immersive Media Inc.",
    role: "Senior Software Engineer",
    period: "Jan 2014 — Jan 2016",
    current: false,
    highlights: [
      "Senior engineering on immersive web products — established frontend standards, API patterns and deployment practices for small teams.",
    ],
    stack: ["JavaScript", "HTML5", "CSS3", "jQuery", "PHP", "MySQL"],
  },
];

export const devRoles = [
  "Converting Figma / Photoshop / Illustrator into production code and design systems",
  "Building and consuming REST APIs — auth, validation and reusable server modules (Node, PHP/Symfony)",
  "Designing database schemas (PostgreSQL, MySQL, MongoDB) and data modeling",
  "Server management: Nginx, PM2, Docker, Linux, Cloudflare and GitHub Actions CI/CD",
  "Implementing SEO + Open Graph and performance budgets (WebP/WebM, sprite sheets, code-split, Lighthouse)",
  "Optimizing load and runtime: minification, atlas packing, RAF batching, 60fps game rendering",
  "Debugging, troubleshooting and production support across the stack",
  "Deploying to VPS/cloud and to Google Play / App Store — owning release end-to-end",
];

// Portfolio — balanced: games for rendering proof + corporate/tools for full-stack proof
export const projects = [
  {
    slug: "dragon-tiger",
    name: "Dragon Tiger",
    category: "Casino Game",
    image: "dragon-tiger.jpg",
    role: "Full-Stack Game Developer — rendering, animation, API & deploy",
    description: "Real-time card game with deterministic animations, server-synced state and certified flow. Full-stack from PixiJS/WebGL to Node/PHP APIs.",
    features: ["PixiJS scene graph + WebGL", "GSAP + RAF batching", "React shell + Node/PHP API sync", "Nginx/PM2 deploy + MySQL"],
    challenge: "60fps card deal & reveal with server-authoritative state on mid-tier Android.",
    solution: "Atlas batching, object pooling, RAF-coalesced ticks and GPU-composited transforms; synced via lightweight REST + MySQL session store.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Node.js", "MySQL", "Nginx"],
    link: "https://lottery.gpistaging.com/Login?game=dragontiger&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "punto-banco",
    name: "Punto Banco",
    category: "Casino Game",
    image: "punto-banco.jpg",
    role: "Full-Stack Game Developer",
    description: "Baccarat variant — table sync, chip physics, settlement and DB-backed result reconciliation.",
    features: ["State-driven UI", "Chip stacking & physics", "Result reconciliation via API"],
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack", "PHP", "MySQL"],
    link: "https://lottery.gpistaging.com/Login?game=puntobanco&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "three-faces",
    name: "Three Faces Baccarat",
    category: "Casino Game",
    image: "3-faces-baccarat.jpg",
    role: "Game Developer",
    description: "Three-hand baccarat with concurrent animations and side-bet UI.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=threefacesbaccarat&vendor=W88&mode=try&lang=en",
    featured: true,
  },
  {
    slug: "domino-qq",
    name: "Domino QQ Virtual Dealer",
    category: "Casino Game",
    image: "domino-qq.jpg",
    role: "Game Developer",
    description: "Domino QQ with virtual dealer — tile layout engine and turn sequencing.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=dominoqqvirtualdealer&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "golden-ball",
    name: "Golden Power Ball",
    category: "Lottery Game",
    image: "golden-power-ball.jpg",
    role: "Game Developer",
    description: "Number-draw lottery with ball physics and draw anticipation.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=goldenpowerball&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "hilo-card",
    name: "HiLo Card",
    category: "Casino Game",
    image: "hilo-card.jpg",
    role: "Game Developer",
    description: "Hi-Lo prediction game — minimal UI, instant feedback and streak tracking.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=hilocard&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "crypto-crash",
    name: "Crypto Crash",
    category: "Real-time Game",
    image: "crypto-crash.png",
    role: "Full-Stack Game Developer — real-time API + game",
    description: "Multiplier curve game — real-time graph, cash-out timing and live player rail via WebSocket/REST.",
    features: ["Real-time graph + WebSocket", "Cash-out race & player rail", "Node API + DB session"],
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Node.js", "PostgreSQL"],
    link: "https://games.crescendoops.com/Login?vendor=W88&s=&lang=en&game=cryptocrash&mode=try",
    featured: true,
  },
  {
    slug: "tambola",
    name: "Tambola Tropika",
    category: "Lottery",
    image: "tambola-tropika.jpg",
    role: "Game Developer",
    description: "Tambola/Housie — ticket generation, number calling and win validation.",
    tech: ["HTML5", "TypeScript", "React", "PixiJS", "GSAP", "Webpack"],
    link: "https://lottery.gpistaging.com/Login?game=tambolatropika&vendor=W88&mode=try&lang=en",
    featured: false,
  },
  {
    slug: "keno",
    name: "Keno Mobile",
    category: "Lottery — Mobile",
    image: "keno.png",
    role: "Frontend / Game Developer",
    description: "Mobile Keno — touch-optimized board, quick-pick and draw history.",
    features: ["React + Redux", "PixiJS board", "React Spring transitions"],
    tech: ["HTML5", "JavaScript", "React", "Redux", "React Spring", "PixiJS"],
    link: "https://crescendogames.studio/Login?vendor=W88&s=&lang=en&game=newkeno&mode=try",
    featured: false,
  },
  {
    slug: "leiprime",
    name: "Lei Prime",
    category: "Corporate Platform",
    image: "leiprime.png",
    role: "Full-Stack Developer — frontend, API, DB & deploy",
    description: "Corporate marketing site — React + Tailwind frontend on headless Symfony/PHP, MySQL, Nginx/PM2 + Cloudflare.",
    challenge: "Needed a fast, SEO-visible corporate presence with editable content, consistent design system and low-ops hosting.",
    solution: "Delivered React + Tailwind on headless Symfony API; modeled MySQL, added OG/SEO, Dockerized Nginx/PM2 and Cloudflare edge cache; Lighthouse-tuned.",
    features: ["React + Tailwind design system", "Headless Symfony PHP API & CMS", "MySQL content modeling", "Nginx + PM2 + Docker + Cloudflare", "SEO & Open Graph + WebP/code-split"],
    tech: ["HTML5", "JavaScript", "React", "Tailwind", "PHP", "Symfony", "MySQL", "Nginx", "Docker", "Cloudflare"],
    link: "https://leiprime.com",
    featured: true,
  },
  {
    slug: "mdc",
    name: "My Dominion Corp",
    category: "Corporate Platform",
    image: "mdc.png",
    role: "Full-Stack Developer — platform, API, DB & infra",
    description: "Business platform — MUI + Tailwind, RBAC, Symfony API, MySQL/PostgreSQL, server management and deployment.",
    challenge: "Required a maintainable business platform with role-based content, secure API and operable DB/infra.",
    solution: "Built MUI + Tailwind with RBAC, Symfony auth/API, normalized MySQL/PostgreSQL, Nginx/PM2 + Docker and GitHub Actions CI.",
    features: ["MUI + Tailwind + RBAC", "Symfony API & auth", "MySQL/PostgreSQL schema", "Nginx/PM2/Docker + Cloudflare", "Responsive + SEO"],
    tech: ["HTML5", "JavaScript", "React", "Tailwind", "MUI", "PHP", "Symfony", "MySQL", "PostgreSQL", "Nginx", "Docker"],
    link: "https://mydominioncorp.com",
    featured: true,
  },
  {
    slug: "css-spritesheet",
    name: "CSS Spritesheet",
    category: "Dev Tool",
    image: "image-tools.svg",
    role: "Solo — open source",
    description: "Browser tool to pack images into CSS spritesheets — drag, pack, export with live preview.",
    challenge: "Manually packing images into CSS sprites requires precise coordinate math and is error-prone for CSS authoring.",
    solution: "Built a client-side Canvas packing engine with drag-drop, live preview and one-click CSS export — no server, instant feedback.",
    features: ["Drag-drop Canvas packing engine", "Live CSS generation & preview", "Retina & coordinate math", "One-click CSS export & copy"],
    tech: ["HTML5", "JavaScript", "CSS3"],
    link: "https://gaciloarielfrancis.github.io/CSS-Spritesheet/",
    featured: false,
    deliveryFocus: "Canvas • drag-drop • CSS export • retina • client-side",
  },
  {
    slug: "gif-to-spritesheet",
    name: "GIF to Spritesheet",
    category: "Dev Tool",
    image: "image-tools.svg",
    role: "Solo — open source",
    description: "Convert GIF frames into sprite sheets for game pipelines — Vite + React + Tailwind.",
    challenge: "Game pipelines need GIF frames as sprite atlases; manual conversion breaks timing and wastes artist time.",
    solution: "Built a Vite + React + Tailwind tool that decodes GIF frames, packs via Canvas, previews playback and exports atlas + JSON.",
    features: ["GIF frame decoding & timing", "Canvas atlas packing", "Vite + React + Tailwind shell", "Atlas JSON & WebP export"],
    tech: ["HTML5", "TypeScript", "React", "Tailwind", "Vite"],
    link: "https://gaciloarielfrancis.github.io/GIF-To-Spritesheet",
    featured: true,
  },
  {
    slug: "playpoints",
    name: "PlayPoints",
    category: "Gaming / Rewards / Entertainment",
    image: "playpoints.webp",
    role: "Solo — open source",
    description: "PlayPoints is an interactive rewards platform where users can play quick and entertaining mini-games to earn points.",
    challenge: "Many online games require significant time commitments, complicated gameplay, or provide entertainment without rewarding player engagement.",
    solution: "PlayPoints provides a collection of fast and easy-to-play mini-games designed for quick entertainment.",
    features: ["Quick Mini-Games", "Earn Points", "Multiple Game Options", "Simple Gameplay", "Points Tracking", "Reward System", "Fast User Experience", "Engaging Platform"],
    tech: ["HTML5", "TypeScript", "Vue 3", "Tailwind", "Vite", "Node", "Express", "Prisma", "PostgreSQL"],
    link: "https://playpoints.net",
    featured: true,
  },
  {
    slug: "artivora",
    name: "Artivora",
    category: "Dev Tool",
    image: "artivora.webp",
    role: "Solo — open source",
    description: "Artivora Studio is a free, no-login AI image generator — turn words into stunning visuals in seconds with Flux, SDXL, SD 3.5 and PixelForge via Pixazo.",
    challenge: "AI image tools often require logins, subscriptions, or complex workflows just to generate a quick visual for game assets and content.",
    solution: "Built a single-page Vue + TypeScript studio on the Pixazo Gateway free tier — prompt, 9 style presets, 4 free models, 5 aspect ratios and batch generation, all in the browser.",
    features: ["Prompt + 9 style presets", "4 free AI models (Flux/SDXL/SD 3.5/PixelForge)", "Batch generation (1/2/4) + CFG/steps/seed", "Download/Copy/Upscale + lightbox"],
    tech: ["HTML5", "TypeScript", "Vue.js", "Tailwind", "Vite", "Pixazo API"],
    link: "https://artivora.pages.dev",
    featured: true,
    deliveryFocus: "Vue 3 + TS • Tailwind v4 • Pixazo Gateway • Vite • Cloudflare Pages",
  },
];
